const { entry: e } = require('./util');

// Base curated animals.
const baseAnimals = [
  e('elephant', 'Large mammal', 'Trunk', 'Tusks', 'Africa and Asia'),
  e('penguin', 'Bird', 'Cannot fly', 'Antarctica', 'Tuxedo look'),
  e('giraffe', 'Very tall', 'Long neck', 'Spots', 'Savannah'),
  e('kangaroo', 'Marsupial', 'Australia', 'Pouch', 'Hops'),
  e('dolphin', 'Marine', 'Intelligent', 'Clicks/whistles', 'Swims in pods'),
  e('panda', 'Black and white', 'Bamboo', 'China', 'Bear family'),
  e('parrot', 'Bird', 'Colorful feathers', 'Can mimic speech', 'Tropical'),
  e('octopus', 'Eight arms', 'Ocean', 'Ink cloud', 'Cephalopod'),
  e('tiger', 'Big cat', 'Orange and black stripes', 'Asia', 'Roars'),
  e('otter', 'River animal', 'Playful', 'Seaweed wraps', 'Uses tools'),
  e('lion', 'Pride leader', 'Savannah', 'Mane', 'Big cat'),
  e('bear', 'Forest dweller', 'Hibernates', 'Claws', 'Powerful'),
  e('wolf', 'Pack animal', 'Howls', 'Canine family', 'Gray or white'),
  e('fox', 'Cunning', 'Bushy tail', 'Red coat', 'Nocturnal'),
  e('deer', 'Herbivore', 'Antlers on males', 'Forest', 'Graceful'),
  e('rabbit', 'Long ears', 'Hops', 'Carrots', 'Burrows'),
  e('mouse', 'Small rodent', 'Whiskers', 'Cheese stereotype', 'Squeaks'),
  e('squirrel', 'Tree climber', 'Bushy tail', 'Acorns', 'Parks'),
  e('beaver', 'Dams', 'Flat tail', 'River engineer', 'Teeth'),
  e('moose', 'Huge deer', 'Antlers', 'North America', 'Swampy areas'),
  e('buffalo', 'Herd animal', 'Horns', 'Prairie', 'Bison'),
  e('yak', 'Long hair', 'Mountains', 'Himalayas', 'Beast of burden'),
  e('goat', 'Horns', 'Mountain climber', 'Milk', 'Bleats'),
  e('sheep', 'Wool', 'Flock', 'Pasture', 'Baa sound'),
  e('cow', 'Dairy or beef', 'Farm', 'Moo', 'Grazes'),
  e('pig', 'Snout', 'Farm', 'Oink', 'Smart'),
  e('horse', 'Mane', 'Rides', 'Hooves', 'Stable'),
  e('donkey', 'Sturdy', 'Brays', 'Carries loads', 'Long ears'),
  e('camel', 'Humps', 'Desert', 'Caravan', 'Spits'),
  e('llama', 'Andes', 'Wool', 'Pack animal', 'Spits too'),
  e('alpaca', 'Soft fleece', 'Andes', 'Grazes', 'Calm'),
  e('zebra', 'Black-white stripes', 'Africa', 'Herds', 'Horse family'),
  e('leopard', 'Spotted cat', 'Stealthy', 'Tree climber', 'Africa/Asia'),
  e('cheetah', 'Fastest land animal', 'Spots', 'Sprint', 'Africa'),
  e('jaguar', 'Big cat', 'Rainforest', 'Rosettes', 'Powerful bite'),
  e('panther', 'Melanistic cat', 'Stealth', 'Black coat', 'Jungle'),
  e('lynx', 'Tufted ears', 'Bobbed tail', 'Snowy forests', 'Stealthy'),
  e('bobcat', 'North America', 'Short tail', 'Spotted', 'Solitary'),
  e('cougar', 'Mountain lion', 'Puma', 'North/South America', 'Stalker'),
  e('hyena', 'Laughing call', 'Scavenger', 'Spotted or striped', 'Savannah'),
  e('coyote', 'Wild dog', 'Howls', 'Desert/grassland', 'North America'),
  e('dingo', 'Wild dog', 'Australia', 'Golden coat', 'Howls'),
  e('badger', 'Burrows', 'Striped face', 'Stout', 'Nocturnal'),
  e('ferret', 'Domesticated', 'Slender', 'Playful', 'Cousin of weasel'),
  e('weasel', 'Slender', 'Predator', 'Burrows', 'Quick'),
  e('hedgehog', 'Spines', 'Rolls up', 'Nocturnal', 'Eats insects'),
  e('porcupine', 'Quills', 'Forest', 'Rodent', 'Slow mover'),
  e('sloth', 'Very slow', 'Tree hanger', 'Rainforest', 'Long claws'),
  e('armadillo', 'Armor plates', 'Burrows', 'Rolls up', 'Americas'),
  e('anteater', 'Long snout', 'Eats ants', 'Sticky tongue', 'Claws'),
  e('wallaby', 'Small kangaroo', 'Australia', 'Hops', 'Marsupial'),
  e('koala', 'Eucalyptus eater', 'Tree hugger', 'Australia', 'Sleepy'),
  e('platypus', 'Duck bill', 'Egg-laying mammal', 'Webbed feet', 'Australia'),
  e('wombat', 'Burrower', 'Cube poop', 'Australia', 'Stocky'),
  e('echidna', 'Spiny anteater', 'Egg-laying mammal', 'Long snout', 'Australia'),
  e('crocodile', 'Reptile', 'Snapping jaws', 'River hunter', 'Scales'),
  e('alligator', 'Reptile', 'Rounded snout', 'Swamp', 'Powerful bite'),
  e('lizard', 'Scales', 'Cold-blooded', 'Sun basker', 'Varies in size'),
  e('gecko', 'Sticky toes', 'No eyelids', 'Clicks', 'Night active'),
  e('chameleon', 'Color change', 'Long tongue', 'Slow', 'Zygodactyl feet'),
  e('iguana', 'Herbivore lizard', 'Spines', 'Tropical', 'Green'),
  e('turtle', 'Shell', 'Slow', 'Reptile', 'Long-lived'),
  e('tortoise', 'Land turtle', 'Domed shell', 'Very slow', 'Herbivore'),
  e('snake', 'No legs', 'Slithers', 'Scales', 'Hisses'),
  e('python', 'Constricter', 'Large', 'Jungle', 'Powerful coils'),
  e('cobra', 'Hood', 'Venomous', 'India', 'Hisses'),
  e('viper', 'Venomous', 'Fangs', 'Triangular head', 'Ambush'),
  e('anaconda', 'Massive snake', 'Swamp', 'Constricter', 'South America'),
  e('frog', 'Amphibian', 'Jumps', 'Croaks', 'Pond'),
  e('toad', 'Warty skin', 'Amphibian', 'Land lover', 'Croaks'),
  e('salamander', 'Amphibian', 'Moist skin', 'Newt cousin', 'Streams'),
  e('newt', 'Small amphibian', 'Moist skin', 'Tail', 'Pond'),
  e('shark', 'Cartilage fish', 'Teeth rows', 'Ocean predator', 'Fin'),
  e('whale', 'Huge marine mammal', 'Blowhole', 'Pods', 'Baleen or toothed'),
  e('orca', 'Black and white', 'Killer whale', 'Pod hunter', 'Intelligent'),
  e('seal', 'Flippers', 'Barks', 'Ocean', 'Beach lounging'),
  e('sea lion', 'Ear flaps', 'Circus performer stereotype', 'Flippers', 'California coast'),
  e('walrus', 'Tusks', 'Mustache whiskers', 'Arctic', 'Blubbery'),
  e('manatee', 'Sea cow', 'Gentle', 'Florida springs', 'Herbivore'),
  e('puffin', 'Colorful beak', 'Sea bird', 'North Atlantic', 'Dives'),
  e('flamingo', 'Pink', 'One-legged stance', 'Filter feeder', 'Flocks'),
  e('ostrich', 'Largest bird', 'Cannot fly', 'Fast runner', 'Long neck'),
  e('emu', 'Australia', 'Large bird', 'Cannot fly', 'Fast runner'),
  e('albatross', 'Long wings', 'Ocean glider', 'Seabird', 'Soars'),
  e('eagle', 'Raptor', 'Sharp talons', 'Soars', 'Symbolic bird'),
  e('hawk', 'Raptor', 'Sharp eyesight', 'Hunts rodents', 'Soars'),
  e('falcon', 'Speedy raptor', 'Pointed wings', 'Dive', 'Peregrine'),
  e('owl', 'Night hunter', 'Silent flight', 'Rotating head', 'Hoot'),
  e('sparrow', 'Small bird', 'Chirps', 'Common', 'Perches'),
  e('robin', 'Red breast', 'Spring bird', 'Chirps', 'Garden'),
  e('bluejay', 'Blue feathers', 'Crest', 'Loud call', 'North America'),
  e('cardinal', 'Red bird', 'Crest', 'Songbird', 'State bird'),
  e('crow', 'Black bird', 'Smart', 'Caws', 'Flocks'),
  e('raven', 'Large black bird', 'Smart', 'Croaks', 'Mythology'),
  e('pigeon', 'City bird', 'Coos', 'Common', 'Rock dove'),
  e('finch', 'Small songbird', 'Seed eater', 'Colorful', 'Perches'),
  e('pelican', 'Big beak pouch', 'Fisher', 'Seaside', 'Group glide'),
  e('stork', 'Long legs', 'Mythical baby bringer', 'Wetlands', 'Migratory'),
  e('heron', 'Long legs', 'Spears fish', 'Wetlands', 'Patient hunter'),
  e('crane', 'Tall bird', 'Dance', 'Wetlands', 'Long neck'),
  e('seagull', 'Coastal bird', 'Scavenger', 'White/gray', 'Squawks'),
  e('bat', 'Only flying mammal', 'Echo-location', 'Nocturnal', 'Wings'),
  e('butterfly', 'Colorful wings', 'Metamorphosis', 'Nectar', 'Flutter'),
  e('moth', 'Nocturnal flyer', 'Attracted to light', 'Scales', 'Cocoons'),
  e('bee', 'Pollinator', 'Honey', 'Hive', 'Stinger'),
  e('wasp', 'Stinger', 'Paper nests', 'Narrow waist', 'Yellow/black'),
  e('ant', 'Colony insect', 'Strong for size', 'Queen', 'Trail pheromones'),
  e('beetle', 'Elytra', 'Many species', 'Hard shell', 'Garden'),
  e('ladybug', 'Red with spots', 'Garden helper', 'Beetle', 'Aphid eater'),
  e('grasshopper', 'Jumps', 'Chirps', 'Green', 'Fields'),
  e('cricket', 'Chirps', 'Night', 'Jumps', 'Brown/green'),
  e('dragonfly', 'Long body', 'Two wing pairs', 'Fast flyer', 'Lakes'),
  e('firefly', 'Bioluminescent', 'Summer nights', 'Blinking', 'Beetle'),
  e('spider', 'Eight legs', 'Webs', 'Arachnid', 'Venomous fangs'),
  e('scorpion', 'Stinger tail', 'Pincers', 'Desert', 'Glows under UV'),
  e('jellyfish', 'Tentacles', 'Stings', 'Drifts', 'Ocean'),
  e('starfish', 'Five arms', 'Regenerates', 'Sea floor', 'Echinoderm'),
  e('crab', 'Sideways walk', 'Claws', 'Shell', 'Beach'),
  e('lobster', 'Claws', 'Shellfish', 'Deep water', 'Red when cooked'),
  e('shrimp', 'Small crustacean', 'Pink when cooked', 'Swims', 'Seafood'),
  e('squid', 'Ten arms', 'Ink', 'Ocean', 'Cephalopod'),
  e('clam', 'Shell', 'Buried in sand', 'Filter feeder', 'Bivalve'),
  e('mussel', 'Shell', 'Rivers or sea', 'Filter feeder', 'Bivalve'),
  e('snail', 'Shell', 'Slow', 'Slime trail', 'Tentacles'),
  e('slug', 'No shell', 'Garden pest', 'Slime', 'Slow'),
];

function fillTo100(list, label, prefix) {
  const out = [...list];
  const seen = new Set(out.map((item) => item.word));
  let i = 1;
  while (out.length < 100) {
    const word = `${prefix}${i}`;
    if (!seen.has(word)) {
      out.push(e(word, `${label} clue ${i}`, `${label} tidbit ${i}`, 'Training filler', 'Replayable item'));
      seen.add(word);
    }
    i += 1;
  }
  return out;
}

module.exports = fillTo100(baseAnimals, 'Animal', 'animalextra');
