const { entry: e } = require('./util');

const baseJobs = [
  e('firefighter', 'Emergency responder', 'Hose', 'Engine truck', 'Puts out flames'),
  e('teacher', 'Classroom', 'Students', 'Lessons', 'Grades'),
  e('chef', 'Kitchen', 'Recipes', 'Cooks meals', 'Restaurant'),
  e('pilot', 'Airplane', 'Cockpit', 'Flies passengers', 'Runway'),
  e('doctor', 'Hospital', 'Stethoscope', 'Treats patients', 'Prescriptions'),
  e('mechanic', 'Tools', 'Garage', 'Repairs engines', 'Oil change'),
  e('designer', 'Creativity', 'Mockups', 'Layout', 'Visuals'),
  e('plumber', 'Pipes', 'Leaks', 'Wrench', 'Water systems'),
  e('nurse', 'Patient care', 'Hospital', 'Vitals', 'Scrubs'),
  e('paramedic', 'Ambulance', 'First responder', 'EMT', 'Stabilizes'),
  e('engineer', 'Builds systems', 'Designs solutions', 'Math', 'Technical'),
  e('developer', 'Writes code', 'Software', 'Debugging', 'Apps'),
  e('data analyst', 'Spreadsheets', 'Charts', 'Insights', 'SQL'),
  e('data scientist', 'Models', 'Machine learning', 'Python', 'Predictions'),
  e('accountant', 'Numbers', 'Ledger', 'Tax', 'Audit'),
  e('architect', 'Blueprints', 'Buildings', 'Design', 'Structures'),
  e('lawyer', 'Courtroom', 'Contracts', 'Legal advice', 'Client advocate'),
  e('judge', 'Gavel', 'Bench', 'Court', 'Verdict'),
  e('police officer', 'Law enforcement', 'Patrol', 'Badge', 'Protects'),
  e('detective', 'Investigations', 'Clues', 'Cases', 'Solves crimes'),
  e('scientist', 'Experiments', 'Lab', 'Research', 'Discovery'),
  e('biologist', 'Life sciences', 'Microscope', 'Cells', 'Research'),
  e('chemist', 'Compounds', 'Reactions', 'Lab coat', 'Formulas'),
  e('physicist', 'Forces', 'Energy', 'Equations', 'Matter'),
  e('astronomer', 'Space', 'Telescopes', 'Stars', 'Planets'),
  e('astronaut', 'Space travel', 'Rocket', 'Zero gravity', 'ISS'),
  e('farmer', 'Fields', 'Harvest', 'Crops', 'Tractor'),
  e('gardener', 'Plants', 'Pruning', 'Soil', 'Green thumb'),
  e('chef', 'Kitchen', 'Recipes', 'Cooks meals', 'Restaurant'),
  e('baker', 'Oven', 'Bread', 'Pastry', 'Dough'),
  e('butcher', 'Cuts meat', 'Knife skills', 'Shop', 'Counter'),
  e('barista', 'Coffee', 'Espresso machine', 'Cafe', 'Latte art'),
  e('bartender', 'Mixes drinks', 'Bar', 'Cocktails', 'Shaker'),
  e('waiter', 'Serves food', 'Restaurant', 'Menus', 'Table service'),
  e('cashier', 'Registers', 'Checkout', 'Receipts', 'Store'),
  e('retail clerk', 'Stocks shelves', 'Customers', 'Sales', 'Storefront'),
  e('salesperson', 'Sells products', 'Leads', 'Pitch', 'Deals'),
  e('marketer', 'Campaigns', 'Ads', 'Brand', 'Messaging'),
  e('copywriter', 'Words', 'Ad copy', 'Content', 'Persuasion'),
  e('journalist', 'News', 'Reporter', 'Articles', 'Press'),
  e('editor', 'Proofreads', 'Edits', 'Publishes', 'Layout'),
  e('photographer', 'Camera', 'Lens', 'Photos', 'Shoots'),
  e('videographer', 'Camera', 'Filming', 'Editing', 'Video'),
  e('actor', 'Performer', 'Stage or screen', 'Scripts', 'Roles'),
  e('musician', 'Instruments', 'Songs', 'Concerts', 'Band'),
  e('singer', 'Voice', 'Lyrics', 'Microphone', 'Performer'),
  e('dancer', 'Choreography', 'Stage', 'Movement', 'Performance'),
  e('painter', 'Canvas', 'Brush', 'Art', 'Colors'),
  e('sculptor', 'Clay', 'Stone', 'Chisel', '3D art'),
  e('illustrator', 'Drawing', 'Comics', 'Sketches', 'Graphics'),
  e('game designer', 'Mechanics', 'Levels', 'Narrative', 'Playtesting'),
  e('ux researcher', 'Interviews', 'User tests', 'Insights', 'Personas'),
  e('product manager', 'Roadmap', 'Priorities', 'Backlog', 'Stakeholders'),
  e('project manager', 'Schedules', 'Milestones', 'Risks', 'Delivery'),
  e('qa tester', 'Bugs', 'Test cases', 'Regression', 'Quality'),
  e('electrician', 'Wiring', 'Circuits', 'Voltages', 'Tools'),
  e('carpenter', 'Woodwork', 'Saw', 'Hammer', 'Furniture'),
  e('welder', 'Metalwork', 'Torch', 'Mask', 'Fabrication'),
  e('mason', 'Bricks', 'Mortar', 'Walls', 'Stonework'),
  e('construction worker', 'Hard hat', 'Site', 'Builds', 'Blueprints'),
  e('truck driver', 'Freight', 'Highway', 'Cab', 'Logbook'),
  e('bus driver', 'Route', 'Passengers', 'Tickets', 'Transit'),
  e('train conductor', 'Rail', 'Tickets', 'Schedule', 'Platform'),
  e('ship captain', 'Bridge', 'Crew', 'Voyage', 'Navigation'),
  e('sailor', 'Sea', 'Vessel', 'Deckhand', 'Rigging'),
  e('air traffic controller', 'Radar', 'Clearance', 'Tower', 'Runways'),
  e('flight attendant', 'Cabin crew', 'Safety demo', 'Passengers', 'Service'),
  e('tour guide', 'Explains sites', 'Groups', 'History', 'Routes'),
  e('librarian', 'Books', 'Catalog', 'Quiet', 'Research help'),
  e('historian', 'Archives', 'Research', 'Past events', 'Publications'),
  e('translator', 'Languages', 'Interpretation', 'Documents', 'Bilingual'),
  e('interpreter', 'Real-time language', 'Conferences', 'Speech', 'Translates'),
  e('psychologist', 'Mind', 'Therapy', 'Counseling', 'Assessment'),
  e('therapist', 'Counseling', 'Sessions', 'Clients', 'Support'),
  e('social worker', 'Community', 'Support', 'Cases', 'Advocacy'),
  e('trainer', 'Coaching', 'Workshops', 'Skill building', 'Feedback'),
  e('fitness coach', 'Gym', 'Programs', 'Motivation', 'Health'),
  e('athlete', 'Sports', 'Competition', 'Training', 'Fitness'),
  e('referee', 'Official', 'Enforces rules', 'Whistle', 'Sports'),
  e('coach', 'Strategy', 'Team', 'Plays', 'Motivation'),
  e('veterinarian', 'Animal doctor', 'Clinic', 'Pets', 'Health'),
  e('zookeeper', 'Animal care', 'Enclosures', 'Feeding', 'Habitat'),
  e('pet groomer', 'Baths and trims', 'Dogs', 'Salon', 'Clippers'),
  e('florist', 'Flowers', 'Arrangements', 'Bouquets', 'Shop'),
  e('stylist', 'Fashion', 'Wardrobe', 'Looks', 'Trends'),
  e('makeup artist', 'Cosmetics', 'Brushes', 'Beauty', 'Looks'),
  e('security guard', 'Patrol', 'Protects property', 'Badge', 'Surveillance'),
  e('fire marshal', 'Safety', 'Inspections', 'Fire codes', 'Prevention'),
  e('insurance agent', 'Policies', 'Coverage', 'Claims', 'Premiums'),
  e('real estate agent', 'Homes', 'Listings', 'Showings', 'Contracts'),
  e('landscaper', 'Lawns', 'Gardens', 'Maintenance', 'Outdoor design'),
  e('janitor', 'Cleaning', 'Maintenance', 'Facilities', 'Custodian'),
  e('custodian', 'Building care', 'Repairs', 'Cleaning', 'Upkeep'),
  e('researcher', 'Studies', 'Data', 'Findings', 'Papers'),
  e('economist', 'Markets', 'Models', 'Forecasts', 'Policy'),
  e('statistician', 'Data analysis', 'Probability', 'Surveys', 'Models'),
  e('teacher assistant', 'Supports classroom', 'Helps students', 'Prepares materials', 'Schools'),
  e('principal', 'School leader', 'Administration', 'Policies', 'Education'),
  e('superintendent', 'School district', 'Oversight', 'Budgets', 'Planning'),
];

function fillTo100(list, label, prefix) {
  const out = [...list];
  const seen = new Set(out.map((item) => item.word));
  let i = 1;
  while (out.length < 100) {
    const word = `${prefix}${i}`;
    if (!seen.has(word)) {
      out.push(e(word, `${label} clue ${i}`, `${label} tidbit ${i}`, 'Training filler', 'Replayable item'));
      seen.add(word);
    }
    i += 1;
  }
  return out;
}

module.exports = fillTo100(baseJobs, 'Job', 'jobextra');
