const { entry: e } = require('./util');

// Packet: Movies (base entries, padded to 50 via packs/index.js)
module.exports = [
  e('inception', 'Dream layers', 'Christopher Nolan', 'Spinning top', 'Leonardo DiCaprio'),
  e('avatar', 'Blue aliens', 'Pandora', 'James Cameron', 'Na-vi'),
  e('gladiator', 'Ancient Rome', 'Arena battles', 'Ridley Scott', 'Are you not entertained?'),
  e('titanic', 'Ocean liner', 'Iceberg', 'Jack and Rose', 'James Cameron'),
  e('matrix', 'Red pill', 'Agents', 'Neo', 'Virtual reality'),
  e('coco', 'Animation', 'Day of the Dead', 'Guitar', 'Pixar'),
  e('rocky', 'Boxing', 'Philadelphia steps', 'Underdog', 'Balboa'),
  e('jaws', 'Shark', 'Amity Island', 'Theme music', 'Steven Spielberg'),
  e('frozen', 'Snow queen', 'Sisters', 'Let it go', 'Disney'),
  e('alien', 'Xenomorph', 'Ripley', 'Chestburster', 'Space horror'),
  e('casablanca', 'Morocco', 'Piano bar', 'Bogart', "Here is looking at you"),
  e('psycho', 'Shower scene', 'Motel', 'Norman Bates', 'Hitchcock'),
  e('godfather', 'Mafia family', 'Don Corleone', 'Offer you cannot refuse', 'Sicily'),
  e('dune', 'Desert planet', 'Spice', 'House Atreides', 'Sandworms'),
  e('up', 'Floating house', 'Balloons', 'Old man Carl', 'Pixar adventure'),
  e('ratatouille', 'Paris kitchen', 'Little chef', 'Remy', 'Cooking rat'),
  e('moana', 'Ocean voyage', 'Heart of Te Fiti', 'Wayfinder', 'Disney'),
  e('encanto', 'Magical family', 'Casita', 'Colombia', 'Bruno'),
  e('spiritedaway', 'Bathhouse', 'No-Face', 'Hayao Miyazaki', 'Chihiro'),
  e('interstellar', 'Space travel', 'Black hole', 'Tesseract', 'Cooper'),
  e('arrival', 'Aliens', 'Linguist', 'Heptapods', 'Time perception'),
  e('parasite', 'South Korea', 'Class divide', 'Basement secret', 'Oscar winner'),
  e('joker', 'Gotham', 'Comedian', 'Arthur Fleck', 'Clown makeup'),
  e('blackpanther', 'Wakanda', 'Vibranium', 'TChalla', 'Marvel hero'),
  e('avengers', 'Team up', 'New York battle', 'Iron Man and Cap', 'Loki'),
  e('endgame', 'Time heist', 'Infinity stones', 'Snap reversal', 'Final battle'),
  e('toy story', 'Talking toys', 'Woody', 'Buzz Lightyear', 'Pixar debut'),
  e('finding nemo', 'Clownfish', 'Ocean search', 'Dory', 'Just keep swimming'),
  e('shrek', 'Ogre', 'Swamp', 'Donkey', 'Fairy tale parody'),
  e('jurassic park', 'Dinosaurs', 'Isla Nublar', 'T. rex', 'Park gone wrong'),
  e('king kong', 'Giant ape', 'Skyscraper climb', 'Skull Island', 'Beauty and the Beast'),
  e('notebook', 'Romance', 'Letters', 'Rain kiss', 'Ryan Gosling'),
  e('la la land', 'Musical', 'Los Angeles', 'Dreamers', 'Emma Stone'),
  e('mad max', 'Post apocalyptic', 'Wasteland', 'Furiosa', 'War Rig'),
  e('blade runner', 'Replicants', 'Deckard', 'Neon city', 'Philip K. Dick'),
  e('skyfall', 'James Bond', 'MI6', 'Adele theme', 'Silva'),
  e('knivesout', 'Whodunit', 'Thrombey mansion', 'Detective Blanc', 'Family secrets'),
  e('mission impossible', 'Ethan Hunt', 'Masks', 'Heists', 'IMF'),
  e('soul', 'Jazz', 'Afterlife', 'Pixar', 'Body swap'),
  e('insideout', 'Emotions', 'Headquarters', 'Joy and Sadness', 'Pixar'),
  e('furyroad', 'Convoy chase', 'Citadel', 'War boys', 'Immortan Joe'),
  e('terminator', 'Cyborg', 'Sarah Connor', "Ill be back", 'Time travel'),
  e('whiplash', 'Drums', 'Jazz band', 'Strict teacher', 'Not my tempo'),
  e('cinderella', 'Glass slipper', 'Midnight', 'Fairy godmother', 'Prince'),
  e('mulan', 'China', 'Warrior disguise', 'Cricket', 'Honor'),
  e('moonstruck', 'Romantic comedy', 'Cher', 'Opera', 'Brooklyn'),
  e('amelie', 'Paris', 'Cafe waitress', 'Quirky deeds', 'Gnome travels'),
  e('goodfellas', 'Mob life', 'Henry Hill', 'Lufthansa heist', 'Funny how?'),
];
