const { entry: e } = require('./util');

const baseObjects = [
  e('laptop', 'Portable', 'Keyboard', 'Screen', 'Computer'),
  e('umbrella', 'Rainy days', 'Handle', 'Canopy', 'Keeps you dry'),
  e('backpack', 'Straps', 'Carry items', 'On your back', 'Zippers'),
  e('headphones', 'Audio', 'Over ears', 'Music', 'Noise cancelling'),
  e('notebook', 'Paper', 'Notes', 'Pages', 'Spiral'),
  e('flashlight', 'Battery', 'Light beam', 'Dark places', 'Torch'),
  e('microwave', 'Kitchen appliance', 'Heats food', 'Turntable', 'Uses waves'),
  e('wallet', 'Holds cash', 'Cards', 'Pocket', 'Foldable'),
  e('smartphone', 'Touchscreen', 'Apps', 'Call', 'Pocket device'),
  e('tablet', 'Touchscreen', 'Bigger than phone', 'Apps', 'Portable'),
  e('monitor', 'Display', 'Desktop', 'Pixels', 'Screen'),
  e('keyboard', 'Keys', 'Typing', 'Input', 'Peripheral'),
  e('mouse', 'Pointer', 'Clicks', 'Scroll wheel', 'Peripheral'),
  e('charger', 'Cable', 'Power', 'Plug', 'Adapter'),
  e('camera', 'Lens', 'Photos', 'Shutter', 'Capture'),
  e('tripod', 'Three legs', 'Stabilizes camera', 'Photography', 'Mount'),
  e('speaker', 'Audio output', 'Music', 'Bluetooth', 'Sound'),
  e('microphone', 'Audio input', 'Recording', 'Podcast', 'Mic'),
  e('television', 'Big screen', 'Remote control', 'Streaming', 'Living room'),
  e('remote', 'Buttons', 'Controls TV', 'Battery powered', 'Handheld'),
  e('sofa', 'Couch', 'Living room', 'Seating', 'Comfort'),
  e('armchair', 'Single seat', 'Cushioned', 'Living room', 'Comfort'),
  e('desk', 'Work surface', 'Office', 'Drawers', 'Table'),
  e('chair', 'Seat', 'Four legs', 'Backrest', 'Furniture'),
  e('lamp', 'Light', 'Lamp shade', 'Bulb', 'Desk or floor'),
  e('book', 'Pages', 'Reading', 'Cover', 'Printed'),
  e('magazine', 'Glossy', 'Articles', 'Monthly', 'Stapled'),
  e('newspaper', 'Daily news', 'Print', 'Sections', 'Columns'),
  e('pen', 'Ink', 'Writes', 'Cap', 'Pocket clip'),
  e('pencil', 'Graphite', 'Eraser', 'Wooden', 'Writes'),
  e('eraser', 'Rubber', 'Removes pencil', 'School', 'Rectangular'),
  e('ruler', 'Straightedge', 'Centimeters', 'Inches', 'Measures'),
  e('scissors', 'Blades', 'Cutting', 'Handles', 'Shears'),
  e('tape', 'Sticky', 'Roll', 'Adhesive', 'Clear'),
  e('glue', 'Sticky liquid', 'Bottle', 'Crafts', 'Adhesive'),
  e('stapler', 'Staples', 'Bind papers', 'Office', 'Desk tool'),
  e('binder', 'Ringed', 'Holds papers', 'Folder', 'Office'),
  e('folder', 'Paper holder', 'Documents', 'Organize', 'Office'),
  e('calendar', 'Dates', 'Months', 'Planning', 'Wall or desk'),
  e('clock', 'Time', 'Hands or digital', 'Wall', 'Ticks'),
  e('watch', 'Wrist', 'Timekeeping', 'Strap', 'Analog or digital'),
  e('backpack', 'Straps', 'Carry items', 'On your back', 'Zippers'),
  e('suitcase', 'Travel bag', 'Wheels', 'Handle', 'Luggage'),
  e('duffel bag', 'Soft bag', 'Shoulder strap', 'Travel', 'Gym'),
  e('wallet', 'Holds cash', 'Cards', 'Pocket', 'Foldable'),
  e('purse', 'Handbag', 'Strap', 'Carries essentials', 'Fashion'),
  e('belt', 'Waist', 'Loops', 'Leather', 'Buckle'),
  e('hat', 'Headwear', 'Brim', 'Fashion', 'Sun shade'),
  e('gloves', 'Hands', 'Warmth', 'Winter', 'Pairs'),
  e('scarf', 'Neck', 'Warmth', 'Winter', 'Fabric'),
  e('jacket', 'Outerwear', 'Zipper', 'Sleeves', 'Warmth'),
  e('shoes', 'Footwear', 'Laces', 'Pair', 'Walk'),
  e('boots', 'Footwear', 'Ankle or higher', 'Laces or zip', 'Sturdy'),
  e('socks', 'Feet', 'Cotton', 'Pairs', 'Comfort'),
  e('blanket', 'Warmth', 'Bed or couch', 'Soft', 'Cover'),
  e('pillow', 'Head support', 'Bed', 'Soft', 'Sleep'),
  e('mattress', 'Bed', 'Springs or foam', 'Comfort', 'Sleep'),
  e('sheet', 'Bedding', 'Covers mattress', 'Cotton', 'Layer'),
  e('duvet', 'Comforter', 'Blanket', 'Warm', 'Bedding'),
  e('towel', 'Absorbent', 'Bath', 'Drying', 'Cotton'),
  e('toothbrush', 'Bristles', 'Dental', 'Handle', 'Daily'),
  e('toothpaste', 'Minty', 'Dental', 'Tube', 'Fluoride'),
  e('soap', 'Cleansing', 'Bar or liquid', 'Bubbles', 'Hygiene'),
  e('shampoo', 'Hair wash', 'Bottle', 'Lather', 'Hygiene'),
  e('conditioner', 'Hair softener', 'Bottle', 'Smoothes', 'Hygiene'),
  e('razor', 'Shaving', 'Blades', 'Handle', 'Grooming'),
  e('mirror', 'Reflection', 'Glass', 'Bathroom', 'Wall mounted'),
  e('comb', 'Teeth', 'Hair', 'Grooming', 'Small'),
  e('brush', 'Bristles', 'Hair or cleaning', 'Handle', 'Grooming'),
  e('broom', 'Sweeping', 'Handle', 'Bristles', 'Floor'),
  e('mop', 'Wet cleaning', 'Handle', 'Absorbent head', 'Floors'),
  e('bucket', 'Container', 'Handle', 'Holds liquids', 'Cleaning'),
  e('vacuum', 'Suction', 'Floor cleaning', 'Bag or bin', 'Power cord'),
  e('trash can', 'Waste bin', 'Lid optional', 'Trash bags', 'Kitchen'),
  e('recycling bin', 'Bottles and paper', 'Blue', 'Sorting', 'Bags'),
  e('fridge', 'Cold storage', 'Shelves', 'Kitchen', 'Appliance'),
  e('oven', 'Baking', 'Heat', 'Kitchen', 'Appliance'),
  e('stove', 'Burners', 'Cooking', 'Gas or electric', 'Kitchen'),
  e('blender', 'Blades', 'Smoothies', 'Pitcher', 'Countertop'),
  e('toaster', 'Slots', 'Bread', 'Breakfast', 'Countertop'),
  e('kettle', 'Boils water', 'Whistles or clicks', 'Tea', 'Handle'),
  e('cutting board', 'Chopping surface', 'Wood or plastic', 'Kitchen', 'Counter'),
  e('knife', 'Blade', 'Cutting', 'Handle', 'Kitchen'),
  e('fork', 'Tines', 'Eating', 'Utensil', 'Metal'),
  e('spoon', 'Bowl shape', 'Eating', 'Utensil', 'Soup or dessert'),
  e('plate', 'Dish', 'Flat', 'Eating', 'Ceramic'),
  e('bowl', 'Dish', 'Curved', 'Soup or cereal', 'Kitchen'),
  e('cup', 'Mug or glass', 'Drinking', 'Handle optional', 'Kitchen'),
  e('pitcher', 'Holds liquids', 'Pour spout', 'Handle', 'Serving'),
  e('thermos', 'Insulated', 'Keeps temperature', 'Bottle', 'Travel'),
  e('water bottle', 'Reusable', 'Hydration', 'Lid', 'Portable'),
  e('flash drive', 'USB', 'Storage', 'Portable', 'Digital files'),
  e('hard drive', 'Storage', 'External or internal', 'Data', 'Spins or SSD'),
  e('router', 'Wi-Fi', 'Internet', 'Antennas', 'Network'),
  e('modem', 'Internet signal', 'Cable or DSL', 'Gateway', 'ISP'),
  e('printer', 'Paper output', 'Ink or laser', 'Documents', 'Office'),
  e('paper shredder', 'Cuts paper', 'Confetti', 'Security', 'Office'),
];

function fillTo100(list, label, prefix) {
  const out = [...list];
  const seen = new Set(out.map((item) => item.word));
  let i = 1;
  while (out.length < 100) {
    const word = `${prefix}${i}`;
    if (!seen.has(word)) {
      out.push(e(word, `${label} clue ${i}`, `${label} tidbit ${i}`, 'Training filler', 'Replayable item'));
      seen.add(word);
    }
    i += 1;
  }
  return out;
}

module.exports = fillTo100(baseObjects, 'Object', 'objectextra');
