const { entry: e } = require('./util');

// Packet: Places
const basePlaces = [
  e('paris', 'Eiffel Tower', 'France', 'City of Light', 'Seine River'),
  e('tokyo', 'Shibuya crossing', 'Japan', 'Sushi capital', 'Skytree'),
  e('sahara', 'Desert', 'Africa', 'Sand dunes', 'Very hot'),
  e('amazon', 'Rainforest', 'South America', 'Largest river by volume', 'Brazil'),
  e('venice', 'Canals', 'Gondolas', 'Italy', 'No cars'),
  e('alps', 'Mountain range', 'Europe', 'Skiing', 'Snowy peaks'),
  e('grand canyon', 'Arizona', 'Red rock', 'Colorado River', 'Deep gorge'),
  e('new york', 'Skyscrapers', 'Times Square', 'Central Park', 'USA'),
  e('london', 'Big Ben', 'Thames', 'UK capital', 'Double-decker buses'),
  e('rome', 'Colosseum', 'Italy', 'Ancient ruins', 'Vatican nearby'),
  e('los angeles', 'Hollywood', 'Beaches', 'Freeways', 'California'),
  e('rio de janeiro', 'Christ the Redeemer', 'Beaches', 'Carnival', 'Brazil'),
  e('cape town', 'Table Mountain', 'South Africa', 'Coastal', 'Cape Point'),
  e('sydney', 'Opera House', 'Harbour Bridge', 'Australia', 'Beaches'),
  e('auckland', 'Harbour city', 'Sky Tower', 'New Zealand', 'Volcano cones'),
  e('dubai', 'Burj Khalifa', 'Desert city', 'UAE', 'Palm islands'),
  e('singapore', 'City-state', 'Gardens by the Bay', 'Marina Bay Sands', 'Strict laws'),
  e('hong kong', 'Skyscrapers', 'Victoria Harbour', 'Dim sum', 'China SAR'),
  e('shanghai', 'Pudong skyline', 'Huangpu River', 'China', 'Bund'),
  e('beijing', 'Forbidden City', 'Capital of China', 'Great Wall nearby', 'Tiananmen'),
  e('moscow', 'Red Square', 'Kremlin', 'Russia', 'Onion domes'),
  e('berlin', 'Brandenburg Gate', 'Germany', 'Berlin Wall history', 'Capital'),
  e('madrid', 'Royal Palace', 'Spain', 'Prado', 'Plaza Mayor'),
  e('barcelona', 'Sagrada Familia', 'Gaudi', 'Spain', 'Las Ramblas'),
  e('amsterdam', 'Canals', 'Bicycles', 'Netherlands', 'Tulips'),
  e('brussels', 'Grand Place', 'Belgium', 'Chocolate', 'EU capital'),
  e('vienna', 'Classical music', 'Austria', 'Hofburg', 'Coffeehouses'),
  e('prague', 'Charles Bridge', 'Czechia', 'Old Town', 'Castle'),
  e('budapest', 'Danube', 'Thermal baths', 'Hungary', 'Parliament'),
  e('istanbul', 'Bosphorus', 'Hagia Sophia', 'Turkey', 'Bridges two continents'),
  e('athens', 'Acropolis', 'Greece', 'Ancient ruins', 'Parthenon'),
  e('cairo', 'Nile', 'Pyramids nearby', 'Egypt', 'Historic'),
  e('lagos', 'Nigeria', 'Megacity', 'Coast', 'Commerce'),
  e('nairobi', 'Kenya', 'Savannah nearby', 'Safari gateway', 'Capital'),
  e('addis ababa', 'Ethiopia', 'High altitude', 'Coffee', 'AU HQ'),
  e('johannesburg', 'South Africa', 'Economic hub', 'Highveld', 'History'),
  e('casablanca', 'Morocco', 'Atlantic port', 'Hassan II Mosque', 'Film namesake'),
  e('lisbon', 'Portugal', 'Trams', 'Seven hills', 'Tagus River'),
  e('porto', 'Portugal', 'Port wine', 'Bridges', 'Ribeira'),
  e('oslo', 'Norway', 'Fjords', 'Opera house', 'Scandinavian'),
  e('stockholm', 'Sweden', 'Archipelago', 'Gamla Stan', 'Scandinavian'),
  e('helsinki', 'Finland', 'Baltic Sea', 'Design', 'Sauna culture'),
  e('copenhagen', 'Denmark', 'Little Mermaid', 'Bicycles', 'Harbor'),
  e('reykjavik', 'Iceland', 'Geothermal', 'Colorful roofs', 'Northern lights'),
  e('dublin', 'Ireland', 'Temple Bar', 'River Liffey', 'Green isle'),
  e('edinburgh', 'Scotland', 'Castle', 'Royal Mile', 'Fringe festival'),
  e('zurich', 'Switzerland', 'Lake', 'Finance', 'Mountains nearby'),
  e('geneva', 'Switzerland', 'UN hub', 'Lake', 'Jet d’Eau'),
  e('miami', 'Florida', 'Beaches', 'Art deco', 'Cuban influence'),
  e('chicago', 'Illinois', 'Windy city', 'Skyscrapers', 'Lake Michigan'),
  e('seattle', 'Washington', 'Space Needle', 'Rain', 'Coffee'),
  e('vancouver', 'Canada', 'Mountains', 'Seaport', 'Stanley Park'),
  e('montreal', 'Canada', 'French influence', 'Old Port', 'Poutine'),
  e('toronto', 'Canada', 'CN Tower', 'Diverse', 'Lake Ontario'),
  e('mexico city', 'Mexico', 'Zocalo', 'High altitude', 'Megacity'),
  e('buenos aires', 'Argentina', 'Tango', 'Obelisk', 'Capital'),
  e('santiago', 'Chile', 'Andes backdrop', 'Plaza de Armas', 'Capital'),
  e('lima', 'Peru', 'Pacific coast', 'Miraflores', 'Cuisine'),
  e('bogota', 'Colombia', 'High altitude', 'La Candelaria', 'Capital'),
  e('quito', 'Ecuador', 'Andes', 'Equator nearby', 'Colonial center'),
  e('caracas', 'Venezuela', 'Avila Mountain', 'Caribbean', 'Capital'),
  e('panama city', 'Panama', 'Canal', 'Skyscrapers', 'Old Town'),
  e('san jose', 'Costa Rica', 'Central valley', 'Capital', 'Museums'),
  e('san juan', 'Puerto Rico', 'Old forts', 'Caribbean', 'Colorful streets'),
  e('honolulu', 'Hawaii', 'Waikiki', 'Beaches', 'Volcanoes'),
  e('las vegas', 'Nevada', 'Strip', 'Casinos', 'Neon lights'),
  e('orlando', 'Florida', 'Theme parks', 'Disney', 'Tourism'),
  e('bangkok', 'Thailand', 'Temples', 'Street food', 'Chao Phraya'),
  e('hanoi', 'Vietnam', 'Old Quarter', 'Capital', 'Lake'),
  e('kuala lumpur', 'Malaysia', 'Petronas Towers', 'Capital', 'Bustling'),
  e('jakarta', 'Indonesia', 'Capital', 'Traffic', 'Islands hub'),
  e('manila', 'Philippines', 'Capital', 'Bay', 'Historic Intramuros'),
  e('delhi', 'India', 'Red Fort', 'Crowded', 'Capital region'),
  e('mumbai', 'India', 'Bollywood', 'Gateway of India', 'Financial hub'),
  e('kolkata', 'India', 'Howrah Bridge', 'Cultural hub', 'Ganges delta'),
  e('karachi', 'Pakistan', 'Port city', 'Largest city', 'Arabian Sea'),
  e('doha', 'Qatar', 'Modern skyline', 'Corniche', 'World Cup host'),
  e('riyadh', 'Saudi Arabia', 'Desert capital', 'Kingdom Centre', 'Modern'),
  e('tehran', 'Iran', 'Capital', 'Alborz Mountains', 'Bazaar'),
  e('istanbul', 'Bosphorus', 'Hagia Sophia', 'Turkey', 'Bridges two continents'),
  e('athens', 'Acropolis', 'Greece', 'Ancient ruins', 'Parthenon'),
];

module.exports = basePlaces;
