const { entry: e } = require('./util');

// Packet: Places (50 entries)
module.exports = [
  e('paris', 'Eiffel Tower', 'France', 'City of Light', 'Seine River'),
  e('tokyo', 'Shibuya crossing', 'Japan', 'Sushi capital', 'Skytree'),
  e('sahara', 'Desert', 'Africa', 'Sand dunes', 'Very hot'),
  e('amazon', 'Rainforest', 'South America', 'Largest river by volume', 'Brazil'),
  e('venice', 'Canals', 'Gondolas', 'Italy', 'No cars'),
  e('alps', 'Mountain range', 'Europe', 'Skiing', 'Snowy peaks'),
  e('bahamas', 'Islands', 'Caribbean', 'Turquoise water', 'Nassau'),
  e('sydney', 'Opera House', 'Harbour Bridge', 'Australia', 'Down Under'),
  e('cairo', 'Egypt', 'Pyramids nearby', 'Nile River', 'Capital city'),
  e('madrid', 'Spain', 'Royal Palace', 'Puerta del Sol', 'La Liga teams'),
  e('rome', 'Colosseum', 'Italy', 'Ancient ruins', 'Vatican nearby'),
  e('london', 'Big Ben', 'UK', 'Thames River', 'Red buses'),
  e('newyork', 'Skyscrapers', 'Times Square', 'USA', 'Central Park'),
  e('losangeles', 'Hollywood', 'Beaches', 'USA', 'City of Angels'),
  e('toronto', 'CN Tower', 'Canada', 'Lake Ontario', 'Diverse city'),
  e('dubai', 'Burj Khalifa', 'UAE', 'Desert city', 'Palm islands'),
  e('singapore', 'Marina Bay', 'Lion city', 'Clean streets', 'Hawker food'),
  e('hongkong', 'Victoria Peak', 'Harbor skyline', 'Dim sum', 'Skyscrapers'),
  e('bangkok', 'Thai capital', 'Street food', 'Chao Phraya', 'Temples'),
  e('delhi', 'India', 'Capital territory', 'Red Fort', 'Crowded'),
  e('istanbul', 'Bosporus', 'Turkey', 'Hagia Sophia', 'Bridges Europe/Asia'),
  e('berlin', 'Brandenburg Gate', 'Germany', 'Wall history', 'Techno scene'),
  e('amsterdam', 'Bicycles', 'Canals', 'Netherlands', 'Anne Frank House'),
  e('athens', 'Acropolis', 'Greece', 'Parthenon', 'Ancient city'),
  e('lisbon', 'Portugal', 'Trams', 'Seven hills', 'Pastel de nata'),
  e('prague', 'Charles Bridge', 'Czechia', 'Old Town', 'Castle on hill'),
  e('vienna', 'Classical music', 'Austria', 'Coffee houses', 'Ringstrasse'),
  e('zurich', 'Switzerland', 'Lake city', 'Finance hub', 'Alps nearby'),
  e('stockholm', 'Sweden', 'Archipelago', 'Gamla Stan', 'Nobel prizes'),
  e('oslo', 'Norway', 'Fjords gateway', 'Opera house', 'Viking ships'),
  e('helsinki', 'Finland', 'Sauna culture', 'Baltic Sea', 'Design district'),
  e('reykjavik', 'Iceland', 'Geothermal pools', 'Northern lights', 'Colorful roofs'),
  e('mexicocity', 'High altitude', 'Zocalo', 'Aztec ruins', 'Tacos galore'),
  e('buenosaires', 'Argentina', 'Tango', 'Obelisco', 'Riverside'),
  e('santiago', 'Chile', 'Andes backdrop', 'Plaza de Armas', 'Wine region'),
  e('lima', 'Peru', 'Pacific coast', 'Ceviche', 'Plaza Mayor'),
  e('bogota', 'Colombia', 'High plateau', 'Monserrate hill', 'Bike culture'),
  e('cape town', 'South Africa', 'Table Mountain', 'Robben Island', 'Two oceans'),
  e('lagos', 'Nigeria', 'Mega city', 'Atlantic coast', 'Busy markets'),
  e('nairobi', 'Kenya', 'Safari gateway', 'Nairobi National Park', 'Capital'),
  e('casablanca', 'Morocco', 'Atlantic port', 'Hassan II Mosque', 'Humphrey Bogart film'),
  e('doha', 'Qatar', 'Corniche', 'World Cup host', 'Desert city'),
  e('auckland', 'New Zealand', 'Harbour City', 'Sky Tower', 'Islands nearby'),
  e('melbourne', 'Australia', 'Laneway cafes', 'Sports capital', 'Trams'),
  e('mumbai', 'India', 'Bollywood', 'Gateway of India', 'Arabian Sea'),
  e('seattle', 'USA', 'Space Needle', 'Rainy', 'Coffee culture'),
  e('chicago', 'USA', 'Windy City', 'Lake Michigan', 'Deep-dish pizza'),
  e('sanfrancisco', 'USA', 'Golden Gate Bridge', 'Hilly streets', 'Cable cars'),
  e('honolulu', 'Hawaii', 'Waikiki', 'Volcanoes nearby', 'Surfing'),
  e('orlando', 'USA', 'Theme parks', 'Florida', 'Mickey Mouse'),
  e('lasvegas', 'USA', 'Strip', 'Casinos', 'Desert lights'),
];
